export const ALL_ARTICLE_REQUEST = "ALL_ARTICLE_REQUEST";
export const ALL_ARTICLE_SUCCESS = "ALL_ARTICLE_SUCCESS";
export const ALL_ARTICLE_FAIL = "ALL_ARTICLE_FAIL";

export const ADMIN_ARTICLE_REQUEST = "ADMIN_ARTICLE_REQUEST";
export const ADMIN_ARTICLE_SUCCESS = "ADMIN_ARTICLE_SUCCESS";
export const ADMIN_ARTICLE_FAIL = "ADMIN_ARTICLE_FAIL";

export const NEW_ARTICLE_REQUEST = "NEW_ARTICLE_REQUEST";
export const NEW_ARTICLE_SUCCESS = "NEW_ARTICLE_SUCCESS";
export const NEW_ARTICLE_RESET = "NEW_ARTICLE_RESET";
export const NEW_ARTICLE_FAIL = "NEW_ARTICLE_FAIL";

export const UPDATE_ARTICLE_REQUEST = "UPDATE_ARTICLE_REQUEST";
export const UPDATE_ARTICLE_SUCCESS = "UPDATE_ARTICLE_SUCCESS";
export const UPDATE_ARTICLE_RESET = "UPDATE_ARTICLE_RESET";
export const UPDATE_ARTICLE_FAIL = "UPDATE_ARTICLE_FAIL";

export const DELETE_ARTICLE_REQUEST = "DELETE_ARTICLE_REQUEST";
export const DELETE_ARTICLE_SUCCESS = "DELETE_ARTICLE_SUCCESS";
export const DELETE_ARTICLE_RESET = "DELETE_ARTICLE_RESET";
export const DELETE_ARTICLE_FAIL = "DELETE_ARTICLE_FAIL";

export const ARTICLE_DETAILS_REQUEST = "ARTICLE_DETAILS_REQUEST";
export const ARTICLE_DETAILS_SUCCESS = "ARTICLE_DETAILS_SUCCESS";
export const ARTICLE_DETAILS_FAIL = "ARTICLE_DETAILS_FAIL";

export const NEW_COMMENT_REQUEST = "NEW_COMMENT_REQUEST";
export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";
export const NEW_COMMENT_RESET = "NEW_COMMENT_RESET";
export const NEW_COMMENT_FAIL = "NEW_COMMENT_FAIL";

export const NEW_UPVOTE_REQUEST = "NEW_UPVOTE_REQUEST";
export const NEW_UPVOTE_SUCCESS = "NEW_UPVOTE_SUCCESS";
export const NEW_UPVOTE_RESET = "NEW_UPVOTE_RESET";
export const NEW_UPVOTE_FAIL = "NEW_UPVOTE_FAIL";

export const NEW_DOWNVOTE_REQUEST = "NEW_DOWNVOTE_REQUEST";
export const NEW_DOWNVOTE_SUCCESS = "NEW_DOWNVOTE_SUCCESS";
export const NEW_DOWNVOTE_RESET = "NEW_DOWNVOTE_RESET";
export const NEW_DOWNVOTE_FAIL = "NEW_DOWNVOTE_FAIL";

export const NEW_SHARE_REQUEST = "NEW_SHARE_REQUEST";
export const NEW_SHARE_SUCCESS = "NEW_SHARE_SUCCESS";
export const NEW_SHARE_RESET = "NEW_SHARE_RESET";
export const NEW_SHARE_FAIL = "NEW_SHARE_FAIL";

export const NEW_LIKE_REQUEST = "NEW_LIKE_REQUEST";
export const NEW_LIKE_SUCCESS = "NEW_LIKE_SUCCESS";
export const NEW_LIKE_RESET = "NEW_LIKE_RESET";
export const NEW_LIKE_FAIL = "NEW_LIKE_FAIL";

export const NEW_SAVE_REQUEST = "NEW_SAVE_REQUEST";
export const NEW_SAVE_SUCCESS = "NEW_SAVE_SUCCESS";
export const NEW_SAVE_RESET = "NEW_SAVE_RESET";
export const NEW_SAVE_FAIL = "NEW_SAVE_FAIL";

export const ALL_COMMENT_REQUEST = "ALL_COMMENT_REQUEST";
export const ALL_COMMENT_SUCCESS = "ALL_COMMENT_SUCCESS";
export const ALL_COMMENT_FAIL = "ALL_COMMENT_FAIL";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_RESET = "DELETE_COMMENT_RESET";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
