export const ALL_IMAGE_REQUEST = "ALL_IMAGE_REQUEST";
export const ALL_IMAGE_SUCCESS = "ALL_IMAGE_SUCCESS";
export const ALL_IMAGE_FAIL = "ALL_IMAGE_FAIL";

export const ADMIN_IMAGE_REQUEST = "ADMIN_IMAGE_REQUEST";
export const ADMIN_IMAGE_SUCCESS = "ADMIN_IMAGE_SUCCESS";
export const ADMIN_IMAGE_FAIL = "ADMIN_IMAGE_FAIL";

export const NEW_IMAGE_REQUEST = "NEW_IMAGE_REQUEST";
export const NEW_IMAGE_SUCCESS = "NEW_IMAGE_SUCCESS";
export const NEW_IMAGE_RESET = "NEW_IMAGE_RESET";
export const NEW_IMAGE_FAIL = "NEW_IMAGE_FAIL";

export const UPDATE_IMAGE_REQUEST = "UPDATE_IMAGE_REQUEST";
export const UPDATE_IMAGE_SUCCESS = "UPDATE_IMAGE_SUCCESS";
export const UPDATE_IMAGE_RESET = "UPDATE_IMAGE_RESET";
export const UPDATE_IMAGE_FAIL = "UPDATE_IMAGE_FAIL";

export const DELETE_IMAGE_REQUEST = "DELETE_IMAGE_REQUEST";
export const DELETE_IMAGE_SUCCESS = "DELETE_IMAGE_SUCCESS";
export const DELETE_IMAGE_RESET = "DELETE_IMAGE_RESET";
export const DELETE_IMAGE_FAIL = "DELETE_IMAGE_FAIL";

export const IMAGE_DETAILS_REQUEST = "IMAGE_DETAILS_REQUEST";
export const IMAGE_DETAILS_SUCCESS = "IMAGE_DETAILS_SUCCESS";
export const IMAGE_DETAILS_FAIL = "IMAGE_DETAILS_FAIL";

export const NEW_COMMENT_REQUEST = "NEW_COMMENT_REQUEST";
export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";
export const NEW_COMMENT_RESET = "NEW_COMMENT_RESET";
export const NEW_COMMENT_FAIL = "NEW_COMMENT_FAIL";

export const ALL_COMMENT_REQUEST = "ALL_COMMENT_REQUEST";
export const ALL_COMMENT_SUCCESS = "ALL_COMMENT_SUCCESS";
export const ALL_COMMENT_FAIL = "ALL_COMMENT_FAIL";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_RESET = "DELETE_COMMENT_RESET";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
