export const ALL_VIDEO_REQUEST = "ALL_VIDEO_REQUEST";
export const ALL_VIDEO_SUCCESS = "ALL_VIDEO_SUCCESS";
export const ALL_VIDEO_FAIL = "ALL_VIDEO_FAIL";

export const ADMIN_VIDEO_REQUEST = "ADMIN_VIDEO_REQUEST";
export const ADMIN_VIDEO_SUCCESS = "ADMIN_VIDEO_SUCCESS";
export const ADMIN_VIDEO_FAIL = "ADMIN_VIDEO_FAIL";

export const NEW_VIDEO_REQUEST = "NEW_VIDEO_REQUEST";
export const NEW_VIDEO_SUCCESS = "NEW_VIDEO_SUCCESS";
export const NEW_VIDEO_RESET = "NEW_VIDEO_RESET";
export const NEW_VIDEO_FAIL = "NEW_VIDEO_FAIL";

export const UPDATE_VIDEO_REQUEST = "UPDATE_VIDEO_REQUEST";
export const UPDATE_VIDEO_SUCCESS = "UPDATE_VIDEO_SUCCESS";
export const UPDATE_VIDEO_RESET = "UPDATE_VIDEO_RESET";
export const UPDATE_VIDEO_FAIL = "UPDATE_VIDEO_FAIL";

export const DELETE_VIDEO_REQUEST = "DELETE_VIDEO_REQUEST";
export const DELETE_VIDEO_SUCCESS = "DELETE_VIDEO_SUCCESS";
export const DELETE_VIDEO_RESET = "DELETE_VIDEO_RESET";
export const DELETE_VIDEO_FAIL = "DELETE_VIDEO_FAIL";

export const VIDEO_DETAILS_REQUEST = "VIDEO_DETAILS_REQUEST";
export const VIDEO_DETAILS_SUCCESS = "VIDEO_DETAILS_SUCCESS";
export const VIDEO_DETAILS_FAIL = "VIDEO_DETAILS_FAIL";

export const NEW_COMMENT_REQUEST = "NEW_COMMENT_REQUEST";
export const NEW_COMMENT_SUCCESS = "NEW_COMMENT_SUCCESS";
export const NEW_COMMENT_RESET = "NEW_COMMENT_RESET";
export const NEW_COMMENT_FAIL = "NEW_COMMENT_FAIL";

export const ALL_COMMENT_REQUEST = "ALL_COMMENT_REQUEST";
export const ALL_COMMENT_SUCCESS = "ALL_COMMENT_SUCCESS";
export const ALL_COMMENT_FAIL = "ALL_COMMENT_FAIL";

export const DELETE_COMMENT_REQUEST = "DELETE_COMMENT_REQUEST";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_RESET = "DELETE_COMMENT_RESET";
export const DELETE_COMMENT_FAIL = "DELETE_COMMENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
